services:
  postgres:
    image: postgres:16
    container_name: tech_challenge_postgres
    restart: always
    environment:
      POSTGRES_DB: tech_challenge
      POSTGRES_USER: rm_user
      POSTGRES_PASSWORD: rm_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rangoapp:
    build: .
    container_name: rangoapp
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${HIBERNATE_DDL_AUTO}


volumes:
  postgres_data:
